---
prometheus:
  url: http://prometheus.localhost/
db:
  dsn: sqlite://./db
  logging: false
config_writer:
  path: /tmp/prom.json
rule_writer:
  rule_path: /tmp/prom.rule
  promtool_path: /path/to/promtool
alert_senders:
  - module: Ikachan
    url: http://ikachan.localhost/
  - module: MailNotify
    smtp_server: smtp.localhost
  - module: Webhook
  - module: Alerta
    alerta_url: http://alerta.localhost
password: foobar
# Default Exporter Settings
# Examples from https://github.com/prometheus/prometheus/wiki/Default-port-allocations
default_exporters:
    node: 9100
    nginx: 9113
    mysqld: 9104
    apache: 9117
